<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kotas = [
            ['id_provinsi' => 1, 'nama_kota' => "KABUPATEN SIMEULUE"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH SINGKIL"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH SELATAN"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH TENGGARA"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH TIMUR"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH TENGAH"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH BARAT"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH BESAR"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN PIDIE"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN BIREUEN"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH UTARA"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH BARAT DAYA"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN GAYO LUES"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH TAMIANG"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN NAGAN RAYA"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH JAYA"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN BENER MERIAH"],
			['id_provinsi' => 1, 'nama_kota' => "KABUPATEN PIDIE JAYA"],
			['id_provinsi' => 1, 'nama_kota' => "KOTA BANDA ACEH"],
			['id_provinsi' => 1, 'nama_kota' => "KOTA SABANG"],
			['id_provinsi' => 1, 'nama_kota' => "KOTA LANGSA"],
			['id_provinsi' => 1, 'nama_kota' => "KOTA LHOKSEUMAWE"],
			['id_provinsi' => 1, 'nama_kota' => "KOTA SUBULUSSALAM"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN NIAS"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN MANDAILING NATAL"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN TAPANULI SELATAN"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN TAPANULI TENGAH"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN TAPANULI UTARA"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN TOBA SAMOSIR"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN LABUHAN BATU"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN ASAHAN"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN SIMALUNGUN"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN DAIRI"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN KARO"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN DELI SERDANG"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN LANGKAT"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN NIAS SELATAN"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN HUMBANG HASUNDUTAN"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN PAKPAK BHARAT"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN SAMOSIR"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN SERDANG BEDAGAI"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN BATU BARA"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN PADANG LAWAS UTARA"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN PADANG LAWAS"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN LABUHAN BATU SELATAN"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN LABUHAN BATU UTARA"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN NIAS UTARA"],
			['id_provinsi' => 2, 'nama_kota' => "KABUPATEN NIAS BARAT"],
			['id_provinsi' => 2, 'nama_kota' => "KOTA SIBOLGA"],
			['id_provinsi' => 2, 'nama_kota' => "KOTA TANJUNG BALAI"],
			['id_provinsi' => 2, 'nama_kota' => "KOTA PEMATANG SIANTAR"],
			['id_provinsi' => 2, 'nama_kota' => "KOTA TEBING TINGGI"],
			['id_provinsi' => 2, 'nama_kota' => "KOTA MEDAN"],
			['id_provinsi' => 2, 'nama_kota' => "KOTA BINJAI"],
			['id_provinsi' => 2, 'nama_kota' => "KOTA PADANGSIDIMPUAN"],
			['id_provinsi' => 2, 'nama_kota' => "KOTA GUNUNGSITOLI"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN KEPULAUAN MENTAWAI"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN PESISIR SELATAN"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN SOLOK"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN SIJUNJUNG"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN TANAH DATAR"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN PADANG PARIAMAN"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN AGAM"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN LIMA PULUH KOTA"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN PASAMAN"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN SOLOK SELATAN"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN DHARMASRAYA"],
			['id_provinsi' => 3, 'nama_kota' => "KABUPATEN PASAMAN BARAT"],
			['id_provinsi' => 3, 'nama_kota' => "KOTA PADANG"],
			['id_provinsi' => 3, 'nama_kota' => "KOTA SOLOK"],
			['id_provinsi' => 3, 'nama_kota' => "KOTA SAWAH LUNTO"],
			['id_provinsi' => 3, 'nama_kota' => "KOTA PADANG PANJANG"],
			['id_provinsi' => 3, 'nama_kota' => "KOTA BUKITTINGGI"],
			['id_provinsi' => 3, 'nama_kota' => "KOTA PAYAKUMBUH"],
			['id_provinsi' => 3, 'nama_kota' => "KOTA PARIAMAN"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN KUANTAN SINGINGI"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN INDRAGIRI HULU"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN INDRAGIRI HILIR"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN PELALAWAN"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN SIAK"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN KAMPAR"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN ROKAN HULU"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN BENGKALIS"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN ROKAN HILIR"],
			['id_provinsi' => 4, 'nama_kota' => "KABUPATEN KEPULAUAN MERANTI"],
			['id_provinsi' => 4, 'nama_kota' => "KOTA PEKANBARU"],
			['id_provinsi' => 4, 'nama_kota' => "KOTA DUMAI"],
			['id_provinsi' => 5, 'nama_kota' => "KABUPATEN KERINCI"],
			['id_provinsi' => 5, 'nama_kota' => "KABUPATEN MERANGIN"],
			['id_provinsi' => 5, 'nama_kota' => "KABUPATEN SAROLANGUN"],
			['id_provinsi' => 5, 'nama_kota' => "KABUPATEN BATANG HARI"],
			['id_provinsi' => 5, 'nama_kota' => "KABUPATEN MUARO JAMBI"],
			['id_provinsi' => 5, 'nama_kota' => "KABUPATEN TANJUNG JABUNG TIMUR"],
			['id_provinsi' => 5, 'nama_kota' => "KABUPATEN TANJUNG JABUNG BARAT"],
			['id_provinsi' => 5, 'nama_kota' => "KABUPATEN TEBO"],
			['id_provinsi' => 5, 'nama_kota' => "KABUPATEN BUNGO"],
			['id_provinsi' => 5, 'nama_kota' => "KOTA JAMBI"],
			['id_provinsi' => 5, 'nama_kota' => "KOTA SUNGAI PENUH"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN KOMERING ULU"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN KOMERING ILIR"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN MUARA ENIM"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN LAHAT"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN MUSI RAWAS"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN MUSI BANYUASIN"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN BANYU ASIN"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN KOMERING ULU SELATAN"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN KOMERING ULU TIMUR"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN ILIR"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN EMPAT LAWANG"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN PENUKAL ABAB LEMATANG ILIR"],
			['id_provinsi' => 6, 'nama_kota' => "KABUPATEN MUSI RAWAS UTARA"],
			['id_provinsi' => 6, 'nama_kota' => "KOTA PALEMBANG"],
			['id_provinsi' => 6, 'nama_kota' => "KOTA PRABUMULIH"],
			['id_provinsi' => 6, 'nama_kota' => "KOTA PAGAR ALAM"],
			['id_provinsi' => 6, 'nama_kota' => "KOTA LUBUKLINGGAU"],
			['id_provinsi' => 7, 'nama_kota' => "KABUPATEN BENGKULU SELATAN"],
			['id_provinsi' => 7, 'nama_kota' => "KABUPATEN REJANG LEBONG"],
			['id_provinsi' => 7, 'nama_kota' => "KABUPATEN BENGKULU UTARA"],
			['id_provinsi' => 7, 'nama_kota' => "KABUPATEN KAUR"],
			['id_provinsi' => 7, 'nama_kota' => "KABUPATEN SELUMA"],
			['id_provinsi' => 7, 'nama_kota' => "KABUPATEN MUKOMUKO"],
			['id_provinsi' => 7, 'nama_kota' => "KABUPATEN LEBONG"],
			['id_provinsi' => 7, 'nama_kota' => "KABUPATEN KEPAHIANG"],
			['id_provinsi' => 7, 'nama_kota' => "KABUPATEN BENGKULU TENGAH"],
			['id_provinsi' => 7, 'nama_kota' => "KOTA BENGKULU"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG BARAT"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN TANGGAMUS"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG SELATAN"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG TIMUR"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG TENGAH"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG UTARA"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN WAY KANAN"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN TULANGBAWANG"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN PESAWARAN"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN PRINGSEWU"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN MESUJI"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN TULANG BAWANG BARAT"],
			['id_provinsi' => 8, 'nama_kota' => "KABUPATEN PESISIR BARAT"],
			['id_provinsi' => 8, 'nama_kota' => "KOTA BANDAR LAMPUNG"],
			['id_provinsi' => 8, 'nama_kota' => "KOTA METRO"],
			['id_provinsi' => 9, 'nama_kota' => "KABUPATEN BANGKA"],
			['id_provinsi' => 9, 'nama_kota' => "KABUPATEN BELITUNG"],
			['id_provinsi' => 9, 'nama_kota' => "KABUPATEN BANGKA BARAT"],
			['id_provinsi' => 9, 'nama_kota' => "KABUPATEN BANGKA TENGAH"],
			['id_provinsi' => 9, 'nama_kota' => "KABUPATEN BANGKA SELATAN"],
			['id_provinsi' => 9, 'nama_kota' => "KABUPATEN BELITUNG TIMUR"],
			['id_provinsi' => 9, 'nama_kota' => "KOTA PANGKAL PINANG"],
			['id_provinsi' => 10, 'nama_kota' => "KABUPATEN KARIMUN"],
			['id_provinsi' => 10, 'nama_kota' => "KABUPATEN BINTAN"],
			['id_provinsi' => 10, 'nama_kota' => "KABUPATEN NATUNA"],
			['id_provinsi' => 10, 'nama_kota' => "KABUPATEN LINGGA"],
			['id_provinsi' => 10, 'nama_kota' => "KABUPATEN KEPULAUAN ANAMBAS"],
			['id_provinsi' => 10, 'nama_kota' => "KOTA BATAM"],
			['id_provinsi' => 10, 'nama_kota' => "KOTA TANJUNG PINANG"],
			['id_provinsi' => 11, 'nama_kota' => "KABUPATEN KEPULAUAN SERIBU"],
			['id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA SELATAN"],
			['id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA TIMUR"],
			['id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA PUSAT"],
			['id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA BARAT"],
			['id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA UTARA"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN BOGOR"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN SUKABUMI"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN CIANJUR"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN BANDUNG"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN GARUT"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN TASIKMALAYA"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN CIAMIS"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN KUNINGAN"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN CIREBON"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN MAJALENGKA"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN SUMEDANG"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN INDRAMAYU"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN SUBANG"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN PURWAKARTA"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN KARAWANG"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN BEKASI"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN BANDUNG BARAT"],
			['id_provinsi' => 12, 'nama_kota' => "KABUPATEN PANGANDARAN"],
			['id_provinsi' => 12, 'nama_kota' => "KOTA BOGOR"],
			['id_provinsi' => 12, 'nama_kota' => "KOTA SUKABUMI"],
			['id_provinsi' => 12, 'nama_kota' => "KOTA BANDUNG"],
			['id_provinsi' => 12, 'nama_kota' => "KOTA CIREBON"],
			['id_provinsi' => 12, 'nama_kota' => "KOTA BEKASI"],
			['id_provinsi' => 12, 'nama_kota' => "KOTA DEPOK"],
			['id_provinsi' => 12, 'nama_kota' => "KOTA CIMAHI"],
			['id_provinsi' => 12, 'nama_kota' => "KOTA TASIKMALAYA"],
			['id_provinsi' => 12, 'nama_kota' => "KOTA BANJAR"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN CILACAP"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN BANYUMAS"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN PURBALINGGA"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN BANJARNEGARA"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN KEBUMEN"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN PURWOREJO"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN WONOSOBO"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN MAGELANG"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN BOYOLALI"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN KLATEN"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN SUKOHARJO"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN WONOGIRI"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN KARANGANYAR"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN SRAGEN"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN GROBOGAN"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN BLORA"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN REMBANG"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN PATI"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN KUDUS"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN JEPARA"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN DEMAK"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN SEMARANG"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN TEMANGGUNG"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN KENDAL"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN BATANG"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN PEKALONGAN"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN PEMALANG"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN TEGAL"],
			['id_provinsi' => 13, 'nama_kota' => "KABUPATEN BREBES"],
			['id_provinsi' => 13, 'nama_kota' => "KOTA MAGELANG"],
			['id_provinsi' => 13, 'nama_kota' => "KOTA SURAKARTA"],
			['id_provinsi' => 13, 'nama_kota' => "KOTA SALATIGA"],
			['id_provinsi' => 13, 'nama_kota' => "KOTA SEMARANG"],
			['id_provinsi' => 13, 'nama_kota' => "KOTA PEKALONGAN"],
			['id_provinsi' => 13, 'nama_kota' => "KOTA TEGAL"],
			['id_provinsi' => 14, 'nama_kota' => "KABUPATEN KULON PROGO"],
			['id_provinsi' => 14, 'nama_kota' => "KABUPATEN BANTUL"],
			['id_provinsi' => 14, 'nama_kota' => "KABUPATEN GUNUNG KIDUL"],
			['id_provinsi' => 14, 'nama_kota' => "KABUPATEN SLEMAN"],
			['id_provinsi' => 14, 'nama_kota' => "KOTA YOGYAKARTA"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN PACITAN"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN PONOROGO"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN TRENGGALEK"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN TULUNGAGUNG"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN BLITAR"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN KEDIRI"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN MALANG"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN LUMAJANG"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN JEMBER"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN BANYUWANGI"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN BONDOWOSO"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN SITUBONDO"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN PROBOLINGGO"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN PASURUAN"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN SIDOARJO"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN MOJOKERTO"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN JOMBANG"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN NGANJUK"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN MADIUN"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN MAGETAN"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN NGAWI"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN BOJONEGORO"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN TUBAN"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN LAMONGAN"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN GRESIK"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN BANGKALAN"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN SAMPANG"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN PAMEKASAN"],
			['id_provinsi' => 15, 'nama_kota' => "KABUPATEN SUMENEP"],
			['id_provinsi' => 15, 'nama_kota' => "KOTA KEDIRI"],
			['id_provinsi' => 15, 'nama_kota' => "KOTA BLITAR"],
			['id_provinsi' => 15, 'nama_kota' => "KOTA MALANG"],
			['id_provinsi' => 15, 'nama_kota' => "KOTA PROBOLINGGO"],
			['id_provinsi' => 15, 'nama_kota' => "KOTA PASURUAN"],
			['id_provinsi' => 15, 'nama_kota' => "KOTA MOJOKERTO"],
			['id_provinsi' => 15, 'nama_kota' => "KOTA MADIUN"],
			['id_provinsi' => 15, 'nama_kota' => "KOTA SURABAYA"],
			['id_provinsi' => 15, 'nama_kota' => "KOTA BATU"],
			['id_provinsi' => 16, 'nama_kota' => "KABUPATEN PANDEGLANG"],
			['id_provinsi' => 16, 'nama_kota' => "KABUPATEN LEBAK"],
			['id_provinsi' => 16, 'nama_kota' => "KABUPATEN TANGERANG"],
			['id_provinsi' => 16, 'nama_kota' => "KABUPATEN SERANG"],
			['id_provinsi' => 16, 'nama_kota' => "KOTA TANGERANG"],
			['id_provinsi' => 16, 'nama_kota' => "KOTA CILEGON"],
			['id_provinsi' => 16, 'nama_kota' => "KOTA SERANG"],
			['id_provinsi' => 16, 'nama_kota' => "KOTA TANGERANG SELATAN"],
			['id_provinsi' => 17, 'nama_kota' => "KABUPATEN JEMBRANA"],
			['id_provinsi' => 17, 'nama_kota' => "KABUPATEN TABANAN"],
			['id_provinsi' => 17, 'nama_kota' => "KABUPATEN BADUNG"],
			['id_provinsi' => 17, 'nama_kota' => "KABUPATEN GIANYAR"],
			['id_provinsi' => 17, 'nama_kota' => "KABUPATEN KLUNGKUNG"],
			['id_provinsi' => 17, 'nama_kota' => "KABUPATEN BANGLI"],
			['id_provinsi' => 17, 'nama_kota' => "KABUPATEN KARANG ASEM"],
			['id_provinsi' => 17, 'nama_kota' => "KABUPATEN BULELENG"],
			['id_provinsi' => 17, 'nama_kota' => "KOTA DENPASAR"],
			['id_provinsi' => 18, 'nama_kota' => "KABUPATEN LOMBOK BARAT"],
			['id_provinsi' => 18, 'nama_kota' => "KABUPATEN LOMBOK TENGAH"],
			['id_provinsi' => 18, 'nama_kota' => "KABUPATEN LOMBOK TIMUR"],
			['id_provinsi' => 18, 'nama_kota' => "KABUPATEN SUMBAWA"],
			['id_provinsi' => 18, 'nama_kota' => "KABUPATEN DOMPU"],
			['id_provinsi' => 18, 'nama_kota' => "KABUPATEN BIMA"],
			['id_provinsi' => 18, 'nama_kota' => "KABUPATEN SUMBAWA BARAT"],
			['id_provinsi' => 18, 'nama_kota' => "KABUPATEN LOMBOK UTARA"],
			['id_provinsi' => 18, 'nama_kota' => "KOTA MATARAM"],
			['id_provinsi' => 18, 'nama_kota' => "KOTA BIMA"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN SUMBA BARAT"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN SUMBA TIMUR"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN KUPANG"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN TIMOR TENGAH SELATAN"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN TIMOR TENGAH UTARA"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN BELU"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN ALOR"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN LEMBATA"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN FLORES TIMUR"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN SIKKA"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN ENDE"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN NGADA"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN MANGGARAI"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN ROTE NDAO"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN MANGGARAI BARAT"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN SUMBA TENGAH"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN SUMBA BARAT DAYA"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN NAGEKEO"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN MANGGARAI TIMUR"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN SABU RAIJUA"],
			['id_provinsi' => 19, 'nama_kota' => "KABUPATEN MALAKA"],
			['id_provinsi' => 19, 'nama_kota' => "KOTA KUPANG"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN SAMBAS"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN BENGKAYANG"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN LANDAK"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN MEMPAWAH"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN SANGGAU"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN KETAPANG"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN SINTANG"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN KAPUAS HULU"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN SEKADAU"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN MELAWI"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN KAYONG UTARA"],
			['id_provinsi' => 20, 'nama_kota' => "KABUPATEN KUBU RAYA"],
			['id_provinsi' => 20, 'nama_kota' => "KOTA PONTIANAK"],
			['id_provinsi' => 20, 'nama_kota' => "KOTA SINGKAWANG"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN KOTAWARINGIN BARAT"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN KOTAWARINGIN TIMUR"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN KAPUAS"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN BARITO SELATAN"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN BARITO UTARA"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN SUKAMARA"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN LAMANDAU"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN SERUYAN"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN KATINGAN"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN PULANG PISAU"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN GUNUNG MAS"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN BARITO TIMUR"],
			['id_provinsi' => 21, 'nama_kota' => "KABUPATEN MURUNG RAYA"],
			['id_provinsi' => 21, 'nama_kota' => "KOTA PALANGKA RAYA"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN TANAH LAUT"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN KOTA BARU"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN BANJAR"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN BARITO KUALA"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN TAPIN"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN HULU SUNGAI SELATAN"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN HULU SUNGAI TENGAH"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN HULU SUNGAI UTARA"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN TABALONG"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN TANAH BUMBU"],
			['id_provinsi' => 22, 'nama_kota' => "KABUPATEN BALANGAN"],
			['id_provinsi' => 22, 'nama_kota' => "KOTA BANJARMASIN"],
			['id_provinsi' => 22, 'nama_kota' => "KOTA BANJAR BARU"],
			['id_provinsi' => 23, 'nama_kota' => "KABUPATEN PASER"],
			['id_provinsi' => 23, 'nama_kota' => "KABUPATEN KUTAI BARAT"],
			['id_provinsi' => 23, 'nama_kota' => "KABUPATEN KUTAI KARTANEGARA"],
			['id_provinsi' => 23, 'nama_kota' => "KABUPATEN KUTAI TIMUR"],
			['id_provinsi' => 23, 'nama_kota' => "KABUPATEN BERAU"],
			['id_provinsi' => 23, 'nama_kota' => "KABUPATEN PENAJAM PASER UTARA"],
			['id_provinsi' => 23, 'nama_kota' => "KABUPATEN MAHAKAM HULU"],
			['id_provinsi' => 23, 'nama_kota' => "KOTA BALIKPAPAN"],
			['id_provinsi' => 23, 'nama_kota' => "KOTA SAMARINDA"],
			['id_provinsi' => 23, 'nama_kota' => "KOTA BONTANG"],
			['id_provinsi' => 24, 'nama_kota' => "KABUPATEN MALINAU"],
			['id_provinsi' => 24, 'nama_kota' => "KABUPATEN BULUNGAN"],
			['id_provinsi' => 24, 'nama_kota' => "KABUPATEN TANA TIDUNG"],
			['id_provinsi' => 24, 'nama_kota' => "KABUPATEN NUNUKAN"],
			['id_provinsi' => 24, 'nama_kota' => "KOTA TARAKAN"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN MINAHASA"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN KEPULAUAN SANGIHE"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN KEPULAUAN TALAUD"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN MINAHASA SELATAN"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN MINAHASA UTARA"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW UTARA"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN SIAU TAGULANDANG BIARO"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN MINAHASA TENGGARA"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW SELATAN"],
			['id_provinsi' => 25, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW TIMUR"],
			['id_provinsi' => 25, 'nama_kota' => "KOTA MANADO"],
			['id_provinsi' => 25, 'nama_kota' => "KOTA BITUNG"],
			['id_provinsi' => 25, 'nama_kota' => "KOTA TOMOHON"],
			['id_provinsi' => 25, 'nama_kota' => "KOTA KOTAMOBAGU"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN BANGGAI KEPULAUAN"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN BANGGAI"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN MOROWALI"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN POSO"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN DONGGALA"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN TOLI-TOLI"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN BUOL"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN PARIGI MOUTONG"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN TOJO UNA-UNA"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN SIGI"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN BANGGAI LAUT"],
			['id_provinsi' => 26, 'nama_kota' => "KABUPATEN MOROWALI UTARA"],
			['id_provinsi' => 26, 'nama_kota' => "KOTA PALU"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN KEPULAUAN SELAYAR"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN BULUKUMBA"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN BANTAENG"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN JENEPONTO"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN TAKALAR"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN GOWA"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN SINJAI"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN MAROS"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN PANGKAJENE DAN KEPULAUAN"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN BARRU"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN BONE"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN SOPPENG"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN WAJO"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN SIDENRENG RAPPANG"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN PINRANG"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN ENREKANG"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN LUWU"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN TANA TORAJA"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN LUWU UTARA"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN LUWU TIMUR"],
			['id_provinsi' => 27, 'nama_kota' => "KABUPATEN TORAJA UTARA"],
			['id_provinsi' => 27, 'nama_kota' => "KOTA MAKASSAR"],
			['id_provinsi' => 27, 'nama_kota' => "KOTA PAREPARE"],
			['id_provinsi' => 27, 'nama_kota' => "KOTA PALOPO"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN BUTON"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN MUNA"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN KONAWE"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN KOLAKA"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN KONAWE SELATAN"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN BOMBANA"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN WAKATOBI"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN KOLAKA UTARA"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN BUTON UTARA"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN KONAWE UTARA"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN KOLAKA TIMUR"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN KONAWE KEPULAUAN"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN MUNA BARAT"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN BUTON TENGAH"],
			['id_provinsi' => 28, 'nama_kota' => "KABUPATEN BUTON SELATAN"],
			['id_provinsi' => 28, 'nama_kota' => "KOTA KENDARI"],
			['id_provinsi' => 28, 'nama_kota' => "KOTA BAUBAU"],
			['id_provinsi' => 29, 'nama_kota' => "KABUPATEN BOALEMO"],
			['id_provinsi' => 29, 'nama_kota' => "KABUPATEN GORONTALO"],
			['id_provinsi' => 29, 'nama_kota' => "KABUPATEN POHUWATO"],
			['id_provinsi' => 29, 'nama_kota' => "KABUPATEN BONE BOLANGO"],
			['id_provinsi' => 29, 'nama_kota' => "KABUPATEN GORONTALO UTARA"],
			['id_provinsi' => 29, 'nama_kota' => "KOTA GORONTALO"],
			['id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAJENE"],
			['id_provinsi' => 30, 'nama_kota' => "KABUPATEN POLEWALI MANDAR"],
			['id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAMASA"],
			['id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAMUJU"],
			['id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAMUJU UTARA"],
			['id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAMUJU TENGAH"],
			['id_provinsi' => 31, 'nama_kota' => "KABUPATEN MALUKU TENGGARA BARAT"],
			['id_provinsi' => 31, 'nama_kota' => "KABUPATEN MALUKU TENGGARA"],
			['id_provinsi' => 31, 'nama_kota' => "KABUPATEN MALUKU TENGAH"],
			['id_provinsi' => 31, 'nama_kota' => "KABUPATEN BURU"],
			['id_provinsi' => 31, 'nama_kota' => "KABUPATEN KEPULAUAN ARU"],
			['id_provinsi' => 31, 'nama_kota' => "KABUPATEN SERAM BAGIAN BARAT"],
			['id_provinsi' => 31, 'nama_kota' => "KABUPATEN SERAM BAGIAN TIMUR"],
			['id_provinsi' => 31, 'nama_kota' => "KABUPATEN MALUKU BARAT DAYA"],
			['id_provinsi' => 31, 'nama_kota' => "KABUPATEN BURU SELATAN"],
			['id_provinsi' => 31, 'nama_kota' => "KOTA AMBON"],
			['id_provinsi' => 31, 'nama_kota' => "KOTA TUAL"],
			['id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA BARAT"],
			['id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA TENGAH"],
			['id_provinsi' => 32, 'nama_kota' => "KABUPATEN KEPULAUAN SULA"],
			['id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA SELATAN"],
			['id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA UTARA"],
			['id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA TIMUR"],
			['id_provinsi' => 32, 'nama_kota' => "KABUPATEN PULAU MOROTAI"],
			['id_provinsi' => 32, 'nama_kota' => "KABUPATEN PULAU TALIABU"],
			['id_provinsi' => 32, 'nama_kota' => "KOTA TERNATE"],
			['id_provinsi' => 32, 'nama_kota' => "KOTA TIDORE KEPULAUAN"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN FAKFAK"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN KAIMANA"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN TELUK WONDAMA"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN TELUK BINTUNI"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN MANOKWARI"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN SORONG SELATAN"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN SORONG"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN RAJA AMPAT"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN TAMBRAUW"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN MAYBRAT"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN MANOKWARI SELATAN"],
			['id_provinsi' => 33, 'nama_kota' => "KABUPATEN PEGUNUNGAN ARFAK"],
			['id_provinsi' => 33, 'nama_kota' => "KOTA SORONG"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN MERAUKE"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN JAYAWIJAYA"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN JAYAPURA"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN NABIRE"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN KEPULAUAN YAPEN"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN BIAK NUMFOR"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN PANIAI"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN PUNCAK JAYA"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN MIMIKA"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN BOVEN DIGOEL"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN MAPPI"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN ASMAT"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN YAHUKIMO"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN PEGUNUNGAN BINTANG"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN TOLIKARA"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN SARMI"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN KEEROM"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN WAROPEN"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN SUPIORI"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN MAMBERAMO RAYA"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN NDUGA"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN LANNY JAYA"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN MAMBERAMO TENGAH"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN YALIMO"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN PUNCAK"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN DOGIYAI"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN INTAN JAYA"],
			['id_provinsi' => 34, 'nama_kota' => "KABUPATEN DEIYAI"],
			['id_provinsi' => 34, 'nama_kota' => "KOTA JAYAPURA"]
			
        ];
        DB::table('kotas')->insert($kotas);
    }
}
